input_data_path: "data/heart.csv"
output_model_path: "models/model.pkl"
metric_path: "models/metrics.json"
splitting_params:
  val_size: 0.1
  random_state: 3
train_params:
  model_type: "RandomForestRegressor"
feature_params:
  categorical_features:
    - sex
    - cp
    - fbs
    - restecg
    - exang
    - ca
    - slope
    - thal
  numerical_features:
  features_to_drop:
  target_col:

