logging_config_path: "ml_project/configs/logging_config.yaml"
input_data_path: "data/heart.csv"
output_model_path: "models/model_lr.pkl"
metric_path: "models/metrics_lr.json"
splitting:
  val_size: 0.2
  random_state: 3
trains:
  model_type: "LogisticRegression"
preprocessing:
  numeric_scaler: "MinMaxScaler"
features:
  categorical_features:
    - sex
    - cp
    - fbs
    - restecg
    - exang
  numerical_features:
    - age
    - trestbps
    - chol
    - thalach
    - oldpeak
  features_to_drop:
  target_col: target

