logging_config_path: "ml_project/configs/logging_config.yaml"
input_data_path: "data/heart.csv"
output_model_path: "models/model_rfc.pkl"
metric_path: "models/metrics_rfc.json"
splitting:
  val_size: 0.1
  random_state: 3
train:
  model_type: "RandomForestClassifier"
preprocessing:
  numeric_scaler: "StandardScaler"
features:
  categorical_features:
    - sex
    - cp
    - fbs
    - restecg
    - exang
    - ca
    - slope
    - thal
  numerical_features:
    - age
    - trestbps
    - chol
    - thalach
    - oldpeak
  features_to_drop:
  target_col: target

