apiVersion: v1
kind: Pod
metadata:
  name: online-inference-pod-probes
  labels:
    app: online-inference
spec:
  containers:
    - image: terysy/online_inference:v3
      name: online-inference
      ports:
        - containerPort: 8000
      readinessProbe:
        httpGet:
          path: /status
          port: 8000
        initialDelaySeconds: 5
        periodSeconds: 5
        failureThreshold: 10
      livenessProbe:
        httpGet:
          path: /status
          port: 8000
        initialDelaySeconds: 60
        periodSeconds: 5
        failureThreshold: 10